### ISSUE TITLE
DOC: add user guide

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#101]
Explain high-level concepts, how to use the package, where to find what. Point to specific examples from the gallery.

- [x] describe high-level organization (PR #124)
- [x] how to create an implant (PR #124)
- [X] how to create a stimulus (PR #119)
- [x] how to run a model (PR #124)
