### ISSUE TITLE
Add basic usage examples to the gallery

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#132]
Implants:
- [x] How to build a custom `p2p.implants.ElectrodeArray` (PR #146)
- [X] How to build a rectangular/hexagonal `p2p.implants.ElectrodeGrid` (PR #162)

Stimuli (@ezgirmak):
- [x] How to build and visualize monophasic/biphasic pulses and some standard pulse trains using `p2p.stimuli.Stimulus` and the pulse trains in `p2p.stimuli.pulse_trains` (PR #133).
- [X] How to build and visualize your own pulse train (sinusoidal: PR #178, others: #180)

Models:
- [X] `ScoreboardModel` (PR #96)
- [X] `AxonMapModel` (PR #96)
- [X] `Nanduri2012Model` (PR #168)
- [X] `Horsager2009Model` (PR #180)

How to:
- On your own fork, make sure you have the upstream repo (`git remote add upstream https://github.com/pulse2percept/pulse2percept.git`)
- Check out the latest version of the `master` branch (`git checkout master && git pull upstream master`)
- Create a new branch off of it (`git checkout -b my-branch`)
- Create a `plot_*.py` file in `doc/examples/{implants|stimuli}`, give it a meaningful name (but it has to start with `plot_` for Sphinx Gallery to work)
- Start the `.py` file with a `"""` block that contains your verbal introduction to the example. You can use Sphinx syntax
- Intersperse your Python code. Add follow-up narrative in `#` comment blocks. Have a look at `doc/examples/models/plot_axonmap.py` or https://sphinx-gallery.github.io/stable/syntax.html for the structure/syntax
- You can build the docs with `make doc` from the root directory or with `make html` from within `doc/`
- git add/commit, make a PR to the upstream `master`

**Comment by ezgirmak** [comment]
Hi all, I can do the stimuli examples.

**Comment by mbeyeler** [comment]
Great!

**Comment by mbeyeler** [comment]
Closed via #180
