### ISSUE TITLE
Speed up AxonMapModel's build process

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#208]
The `build` method of `AxonMapModel` can be sped up. We need it for VR.

- [X] Prune axon segments that don't contribute much to brightness (PR #215)
- [X] Use KDTree to speed up `find_closest_axon` (PR #331)
- [X] Focus on the resulting [axon segment array](https://github.com/pulse2percept/pulse2percept/blob/master/pulse2percept/models/beyeler2019.py#L366) and its start/end index arrays. Build it up in parallel using Cython. (PR #369)
